### ISSUE TITLE
Document why "The most magical of the factory methods" is useful

### ISSUE THREAD

**Issue by schmmd** [allenai/pipeline#4]
https://github.com/allenai/pipeline/blob/io-refactor/src/main/scala/org/allenai/pipeline/PipelineStep.scala#L77

**Comment by schmmd** [comment]
Documentation would help on the other methods here too.  I don't really get why they exist.

**Comment by rodneykinney** [comment]
https://github.com/allenai/pipeline/commit/679b9107d07e3ed931c3244d48531da7002664d9
